{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import xml.etree.ElementTree as ET\n",
    "import mysql.connector\n",
    "import logging\n",
    "import uuid"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "def connect_to_db():\n",
    "    return mysql.connector.connect(\n",
    "        host=\"localhost\",\n",
    "        user=\"root\",\n",
    "        password=\"ftu58fqs\",\n",
    "        database=\"mydb\"\n",
    "    )\n",
    "\n",
    "ns = {'ns': 'http://www.battlescribe.net/schema/catalogueSchema'}\n",
    "\n",
    "def insert_faction(root, cursor):\n",
    "    _name = root.get('name')\n",
    "    _description = root.get('description')\n",
    "    if _description is None:\n",
    "        _description = \"\"\n",
    "    _id = root.get('id')\n",
    "\n",
    "    sql = \"INSERT INTO Faction (name, description, id) VALUES (%s, %s,%s)\"\n",
    "    try:\n",
    "        cursor.execute(sql, (_name, _description, _id))\n",
    "    except Exception as e:\n",
    "        logging.error(\"Error at %s\", \"insert_faction\", exc_info=e)\n",
    "        print(e)\n",
    "\n",
    "    return _id\n",
    "\n",
    "def insert_unit2(cursor, root, faction_id):\n",
    "    sharedSelectionEntries = root.find('ns:sharedSelectionEntries', ns)\n",
    "    for selectionEntry in sharedSelectionEntries:\n",
    "        if \"[Legends]\" not in selectionEntry.get(\"name\"):\n",
    "            if selectionEntry.get(\"type\") == \"model\" or selectionEntry.get(\"type\") == \"unit\":\n",
    "\n",
    "                _name = selectionEntry.get(\"name\")\n",
    "                _description = selectionEntry.get(\"description\")\n",
    "                _description = \"\"\n",
    "                _id = selectionEntry.get(\"id\")\n",
    "\n",
    "                sql = \"INSERT INTO Unit (name, description, id, faction_id) VALUES (%s, %s,%s,%s)\"\n",
    "                try:\n",
    "                    cursor.execute(sql, (_name, _description, _id, faction_id))\n",
    "                    parse_selectionEntry(cursor, selectionEntry, _id)\n",
    "                    insert_keywords(cursor, selectionEntry, _id)\n",
    "                except Exception as e:\n",
    "                    logging.error(\"Error at %s\", \"insert_unit\", exc_info=e)\n",
    "                    print(e)\n",
    "\n",
    "def insert_keywords(cursor, selectionEntry, unit_id):\n",
    "    keywords = selectionEntry.findall(\".//ns:categoryLink\", ns)\n",
    "    for keyword in keywords:\n",
    "        _name = keyword.get(\"name\")\n",
    "        _id = keyword.get(\"targetId\")\n",
    "        sql = \"INSERT IGNORE INTO ModelKeyWord (text, id) VALUES (%s, %s)\"\n",
    "        sql_map = \"INSERT IGNORE INTO unit_has_ModelKeyword (Unit_id, ModelKeyword_id) VALUES (%s, %s)\"\n",
    "        try:\n",
    "            cursor.execute(sql, (_name, _id))\n",
    "            cursor.execute(sql_map, (unit_id, _id))\n",
    "        except Exception as e:\n",
    "            logging.error(\"Error at %s\", \"insert_keywords\", exc_info=e)\n",
    "            print(e)\n",
    "\n",
    "def parse_selectionEntry(cursor, selectionEntry, unit_id):\n",
    "    profiles = selectionEntry.findall(\".//ns:profile\", ns)\n",
    "\n",
    "    for profile in profiles:\n",
    "        if profile.get(\"typeName\") == \"Unit\" or profile.get(\"typeName\") == \"Model\":\n",
    "            insert_model(cursor, profile, unit_id)\n",
    "        if profile.get(\"typeName\") == \"Abilities\":\n",
    "            insert_abilities(cursor, profile, unit_id)\n",
    "        if profile.get(\"typeName\") == \"Ranged Weapons\" or profile.get(\"typeName\") == \"Melee Weapons\":\n",
    "            insert_weapons(cursor, profile, unit_id)\n",
    "\n",
    "def insert_weapons(cursor, profile, unit_id):\n",
    "    _name = profile.get(\"name\")\n",
    "    _id = profile.get(\"id\")\n",
    "    c = profile.find(\".//ns:characteristics\", ns)\n",
    "\n",
    "    _range = None\n",
    "    _strength = None\n",
    "    _ap = None\n",
    "    _damage = None\n",
    "    _attack = None\n",
    "    _hit = None\n",
    "\n",
    "\n",
    "    for characteristic in c:\n",
    "        if characteristic.get(\"name\") == \"Range\":\n",
    "            _range = characteristic.text\n",
    "        if characteristic.get(\"name\") == \"S\":\n",
    "            _strength = characteristic.text\n",
    "        if characteristic.get(\"name\") == \"AP\":\n",
    "            _ap = characteristic.text\n",
    "        if characteristic.get(\"name\") == \"D\":\n",
    "            _damage = characteristic.text\n",
    "        if characteristic.get(\"name\") == \"A\":\n",
    "            _attack = characteristic.text\n",
    "        if characteristic.get(\"name\") == \"WS\":\n",
    "            _hit = characteristic.text\n",
    "        if characteristic.get(\"name\") == \"BS\":\n",
    "            _hit = characteristic.text\n",
    "        if characteristic.get(\"name\") == \"Keywords\":\n",
    "            print(\"insert_weapon_keywords\")\n",
    "            insert_weapon_keywords(cursor, characteristic, _id)\n",
    "\n",
    "    sql = \"INSERT INTO weapon (name, weapon_range, hit_skill, strength, armor_piercing, damage, id, attack, unit_id) VALUES (%s, %s,%s,%s,%s,%s,%s,%s,%s)\"\n",
    "\n",
    "    try:\n",
    "        cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
    "    except Exception as e:\n",
    "        logging.error(\"Error at %s\", \"insert_weapons\", exc_info=e)\n",
    "        print(\"error!!!!\")\n",
    "        print(e)\n",
    "\n",
    "def insert_weapon_keywords(cursor, characteristic, weapon_id):\n",
    "    _keywords = characteristic.text\n",
    "    # Check if the weapon has keywords\n",
    "    if len(_keywords) < 3:\n",
    "        return\n",
    "    keywords = characteristic.text.split(\", \")\n",
    "\n",
    "    for keyword in keywords:\n",
    "        print(keyword)\n",
    "\n",
    "        if keyword.replace(\"/n\", \"\").replace(\" \", \"\") == \"\":\n",
    "            continue\n",
    "\n",
    "        sql = \"select * from weaponkeyword where name = %s\"\n",
    "        print(\"check1\")\n",
    "        cursor.execute(sql, (keyword,))\n",
    "        result = cursor.fetchone()\n",
    "        print(\"check2\")\n",
    "        if result is None or len(result) == 0:\n",
    "            sql = \"INSERT INTO weaponkeyword (name) VALUES (%s)\"\n",
    "            cursor.execute(sql, (keyword,))\n",
    "            cursor.execute(\"SELECT id FROM weaponkeyword WHERE name = %s\", (keyword,))\n",
    "            result = cursor.fetchone()\n",
    "\n",
    "            print(\"result\", keyword)\n",
    "            print(result)\n",
    "            print(type(result))\n",
    "\n",
    "        sql = \"INSERT IGNORE INTO WeaponKeyWord (text, id) VALUES (%s, %s)\"\n",
    "\n",
    "def insert_abilities(cursor, profile, unit_id):\n",
    "    _name = profile.get(\"name\")\n",
    "    _id = profile.get(\"id\")\n",
    "    _description = profile.findall(\".//ns:characteristic\", ns)[0].text\n",
    "\n",
    "    sql = \"INSERT INTO modelability (name, description, id) VALUES (%s, %s,%s)\"\n",
    "    sql_map = \"INSERT INTO unit_has_modelability (unit_id, ModelAbility_id) VALUES (%s, %s)\"\n",
    "    try:\n",
    "        cursor.execute(sql, (_name, _description, _id))\n",
    "        cursor.execute(sql_map, (unit_id, _id))\n",
    "    except Exception as e:\n",
    "        logging.error(\"Error at %s\", \"insert_abilities\", exc_info=e)\n",
    "        print(e)\n",
    "\n",
    "def insert_model(cursor, model, unit_id):\n",
    "    _name = model.get(\"name\")\n",
    "    _id = model.get(\"id\")\n",
    "\n",
    "    move = None\n",
    "    leadership = None\n",
    "    save = None\n",
    "    toughness = None\n",
    "    wounds = None\n",
    "    oc = None\n",
    "    keywords = []\n",
    "    for characteristics in model.findall(\".//ns:characteristic\", ns):\n",
    "\n",
    "        if characteristics.get(\"name\") == \"M\":\n",
    "            move = characteristics.text\n",
    "        elif characteristics.get(\"name\") == \"LD\":\n",
    "            leadership = characteristics.text\n",
    "        elif characteristics.get(\"name\") == \"SV\":\n",
    "            save = characteristics.text\n",
    "        elif characteristics.get(\"name\") == \"T\":\n",
    "            toughness = characteristics.text\n",
    "        elif characteristics.get(\"name\") == \"W\":\n",
    "            wounds = characteristics.text\n",
    "        elif characteristics.get(\"name\") == \"OC\":\n",
    "            oc = characteristics.text\n",
    "\n",
    "\n",
    "        sql_models = \"INSERT INTO Model (id, name, move, toughness,wounds, leadership, save, unit_id, oc) VALUES (%s, %s,%s,%s, %s, %s,%s,%s,%s)\"\n",
    "\n",
    "\n",
    "    try:\n",
    "        cursor.execute(sql_models, (_id, _name, move, toughness, wounds, leadership, save, unit_id, oc))\n",
    "\n",
    "    except Exception as e:\n",
    "        logging.error(\"Error at %s\", \"insert_model\", exc_info=e)\n",
    "        print(e)\n",
    "\n",
    "def parse_cat_file(filename):\n",
    "    tree = ET.parse(filename)\n",
    "    root = tree.getroot()\n",
    "    return root\n",
    "\n",
    "def ingest_data(root, cursor):\n",
    "    faction_id = insert_faction(root, cursor)\n",
    "    insert_unit2(cursor, root, faction_id)\n",
    "    db_connection.commit()\n",
    "\n",
    "def clear_all_tables(cursor):\n",
    "    # Get all table names\n",
    "\n",
    "    # Iterate over all tables and delete all records\n",
    "    try:\n",
    "        cursor.execute(f\"DELETE FROM `CanTakeAsAllied`\")\n",
    "        cursor.execute(f\"DELETE FROM `WeaponHasKeyword`\")\n",
    "        cursor.execute(f\"DELETE FROM `WeaponKeyword`\")\n",
    "        cursor.execute(f\"DELETE FROM `Unit_has_ModelKeyword`\")\n",
    "        cursor.execute(f\"DELETE FROM `Weapon`\")\n",
    "        cursor.execute(f\"DELETE FROM `Model`\")\n",
    "        cursor.execute(f\"DELETE FROM `ModelKeyword`\")\n",
    "        cursor.execute(f\"DELETE FROM `Unit_has_ModelAbility`\")\n",
    "        cursor.execute(f\"DELETE FROM `ModelAbility`\")\n",
    "        cursor.execute(f\"DELETE FROM `UnitCost`\")\n",
    "        cursor.execute(f\"DELETE FROM `SpecialRules`\")\n",
    "        cursor.execute(f\"DELETE FROM `Unit`\")\n",
    "        cursor.execute(f\"DELETE FROM `Faction`\")\n",
    "\n",
    "        db_connection.commit()\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    except mysql.connector.Error as err:\n",
    "        print(f\"Something went wrong: {err}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {
    "collapsed": false
   },
   "outputs": [],
   "source": [
    "db_connection = connect_to_db()\n",
    "cursor = db_connection.cursor(buffered=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'attack' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'damage' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'attack' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "result Lethal Hits\n",
      "(1,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "Pistol\n",
      "check1\n",
      "check2\n",
      "result Pistol\n",
      "(2,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Pistol\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Hazardous\n",
      "check1\n",
      "check2\n",
      "result Hazardous\n",
      "(3,)\n",
      "<class 'tuple'>\n",
      "Pistol\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Anti-INFANTRY 4+\n",
      "check1\n",
      "check2\n",
      "result Anti-INFANTRY 4+\n",
      "(4,)\n",
      "<class 'tuple'>\n",
      "Devastating Wounds\n",
      "check1\n",
      "check2\n",
      "result Devastating Wounds\n",
      "(5,)\n",
      "<class 'tuple'>\n",
      "Rapid Fire 1\n",
      "check1\n",
      "check2\n",
      "result Rapid Fire 1\n",
      "(6,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Anti-INFANTRY 4+\n",
      "check1\n",
      "check2\n",
      "Devastating Wounds\n",
      "check1\n",
      "check2\n",
      "Rapid Fire 1\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Anti-INFANTRY 2+\n",
      "check1\n",
      "check2\n",
      "result Anti-INFANTRY 2+\n",
      "(7,)\n",
      "<class 'tuple'>\n",
      "Ignores Cover\n",
      "check1\n",
      "check2\n",
      "result Ignores Cover\n",
      "(8,)\n",
      "<class 'tuple'>\n",
      "Torrent\n",
      "check1\n",
      "check2\n",
      "result Torrent\n",
      "(9,)\n",
      "<class 'tuple'>\n",
      "Twin-linked\n",
      "check1\n",
      "check2\n",
      "result Twin-linked\n",
      "(10,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Psychic\n",
      "check1\n",
      "check2\n",
      "result Psychic\n",
      "(11,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Anti-VEHICLE 3+\n",
      "check1\n",
      "check2\n",
      "result Anti-VEHICLE 3+\n",
      "(12,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Twin-linked\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Psychic\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Hazardous\n",
      "check1\n",
      "check2\n",
      "Psychic\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'attack' at row 1\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "Psychic\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Psychic\n",
      "check1\n",
      "check2\n",
      "Torrent\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "insert_weapon_keywords\n",
      "Hazardous\n",
      "check1\n",
      "check2\n",
      "Psychic\n",
      "check1\n",
      "check2\n",
      "Torrent\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "insert_weapon_keywords\n",
      "Melta 2\n",
      "check1\n",
      "check2\n",
      "result Melta 2\n",
      "(13,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Anti-INFANTRY 4+\n",
      "check1\n",
      "check2\n",
      "Ignores Cover\n",
      "check1\n",
      "check2\n",
      "Torrent\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "insert_weapon_keywords\n",
      "Ignores Cover\n",
      "check1\n",
      "check2\n",
      "Torrent\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "insert_weapon_keywords\n",
      "Rapid Fire 3\n",
      "check1\n",
      "check2\n",
      "result Rapid Fire 3\n",
      "(14,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Blast\n",
      "check1\n",
      "check2\n",
      "result Blast\n",
      "(15,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Anti-INFANTRY 2+\n",
      "check1\n",
      "check2\n",
      "Ignores Cover\n",
      "check1\n",
      "check2\n",
      "Torrent\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "insert_weapon_keywords\n",
      "Assault\n",
      "check1\n",
      "check2\n",
      "result Assault\n",
      "(16,)\n",
      "<class 'tuple'>\n",
      "Blast\n",
      "check1\n",
      "check2\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Pistol\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Pistol\n",
      "check1\n",
      "check2\n",
      "Sustained Hits D3\n",
      "check1\n",
      "check2\n",
      "result Sustained Hits D3\n",
      "(17,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Hazardous\n",
      "check1\n",
      "check2\n",
      "Pistol\n",
      "check1\n",
      "check2\n",
      "Sustained Hits D3\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Melta 2\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Twin-linked\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Blast\n",
      "check1\n",
      "check2\n",
      "Hazardous\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Blast\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'damage' at row 1\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "Rapid Fire 2\n",
      "check1\n",
      "check2\n",
      "result Rapid Fire 2\n",
      "(18,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Anti-INFANTRY 4+\n",
      "check1\n",
      "check2\n",
      "Devastating Wounds\n",
      "check1\n",
      "check2\n",
      "Rapid Fire 1\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Devastating Wounds\n",
      "check1\n",
      "check2\n",
      "Sustained Hits 1\n",
      "check1\n",
      "check2\n",
      "result Sustained Hits 1\n",
      "(19,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'attack' at row 1\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Blast\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Melta 2\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Anti-INFANTRY 2+\n",
      "check1\n",
      "check2\n",
      "Ignores Cover\n",
      "check1\n",
      "check2\n",
      "Torrent\n",
      "check1\n",
      "check2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'attack' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'damage' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'damage' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'damage' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'attack' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'damage' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'attack' at row 1\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.IntegrityError: 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "ERROR:root:Error at insert_weapons\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Temp\\ipykernel_10436\\1167534344.py\", line 110, in insert_weapons\n",
      "    cursor.execute(sql, (_name, _range, _hit, _strength, _ap, _damage, _id, _attack, unit_id))\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\cursor.py\", line 748, in execute\n",
      "    self._handle_result(self._connection.cmd_query(stmt))\n",
      "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\opentelemetry\\context_propagation.py\", line 102, in wrapper\n",
      "    return method(cnx, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 861, in cmd_query\n",
      "    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))\n",
      "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\Mads\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\mysql\\connector\\connection.py\", line 637, in _handle_result\n",
      "    raise get_exception(packet)\n",
      "mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'hit_skill' at row 1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Blast\n",
      "check1\n",
      "check2\n",
      "Indirect Fire\n",
      "check1\n",
      "check2\n",
      "result Indirect Fire\n",
      "(20,)\n",
      "<class 'tuple'>\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'attack' at row 1\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "Rapid Fire 3\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'damage' at row 1\n",
      "insert_weapon_keywords\n",
      "Anti-INFANTRY 2+\n",
      "check1\n",
      "check2\n",
      "Ignores Cover\n",
      "check1\n",
      "check2\n",
      "Torrent\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'damage' at row 1\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Twin-linked\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'damage' at row 1\n",
      "insert_weapon_keywords\n",
      "Rapid Fire 2\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Blast\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'attack' at row 1\n",
      "insert_weapon_keywords\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'damage' at row 1\n",
      "insert_weapon_keywords\n",
      "Devastating Wounds\n",
      "check1\n",
      "check2\n",
      "Sustained Hits 1\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Twin-linked\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n",
      "insert_weapon_keywords\n",
      "Extra Attacks\n",
      "check1\n",
      "check2\n",
      "result Extra Attacks\n",
      "(21,)\n",
      "<class 'tuple'>\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Blast\n",
      "check1\n",
      "check2\n",
      "Devastating Wounds\n",
      "check1\n",
      "check2\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "Psychic\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'attack' at row 1\n",
      "insert_weapon_keywords\n",
      "Pistol\n",
      "check1\n",
      "check2\n",
      "Sustained Hits D3\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Lethal Hits\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`mydb`.`weapon`, CONSTRAINT `fk_Weapon_Model1` FOREIGN KEY (`unit_id`) REFERENCES `model` (`id`))\n",
      "insert_weapon_keywords\n",
      "Ignores Cover\n",
      "check1\n",
      "check2\n",
      "Torrent\n",
      "check1\n",
      "check2\n",
      "error!!!!\n",
      "1406 (22001): Data too long for column 'hit_skill' at row 1\n"
     ]
    }
   ],
   "source": [
    "root = parse_cat_file(\"./wh40k-10e/Chaos - Death Guard.cat\")\n",
    "clear_all_tables(cursor)\n",
    "ingest_data(root, cursor)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
